# Generated by Django 5.2.1 on 2025-06-05 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    OldCategory = apps.get_model('main', 'Category')
    Category = apps.get_model('blog', 'Category')

    categories = [Category(name_es=cat.name_es, name_en=cat.name_en, slug=cat.slug, color=cat.color) for cat in OldCategory.objects.all()]
    Category.objects.bulk_create(categories)


def reverse_migrate_categories(apps, schema_editor):
    OldCategory = apps.get_model('main', 'Category')
    Category = apps.get_model('blog', 'Category')

    categories = [OldCategory(name_es=cat.name_es, name_en=cat.name_en, slug=cat.slug, color=cat.color) for cat in Category.objects.all()]
    OldCategory.objects.bulk_create(categories)


def migrate_posts(apps, schema_editor):
    OldPost = apps.get_model('main', 'Post')
    Post = apps.get_model('blog', 'Post')
    Category = apps.get_model('blog', 'Category')

    posts = [Post(
        slug=post.slug,
        title_es=post.title_es,
        title_en=post.title_en,
        body_es=post.body_es,
        body_en=post.body_en,
        description_es=post.description_es,
        description_en=post.description_en,
        cover=post.cover,
        category=Category.objects.get(slug=post.category.slug),
        read_time=post.read_time
    ) for post in OldPost.objects.all()]
    Post.objects.bulk_create(posts)


def reverse_migrate_posts(apps, schema_editor):
    OldPost = apps.get_model('main', 'Post')
    Post = apps.get_model('blog', 'Post')
    OldCategory = apps.get_model('main', 'Category')

    posts = [OldPost(
        slug=post.slug,
        title_es=post.title_es,
        title_en=post.title_en,
        body_es=post.body_es,
        body_en=post.body_en,
        description_es=post.description_es,
        description_en=post.description_en,
        cover=post.cover,
        category=OldCategory.objects.get(slug=post.category.slug),
        read_time=post.read_time
    ) for post in Post.objects.all()]
    OldPost.objects.bulk_create(posts)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name_es', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('color', models.CharField(max_length=120)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_categories, reverse_migrate_categories),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title_es', models.CharField(max_length=60)),
                ('title_en', models.CharField(max_length=60)),
                ('body_es', models.TextField()),
                ('body_en', models.TextField()),
                ('description_es', models.CharField(max_length=160)),
                ('description_en', models.CharField(max_length=160)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('read_time', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_posts, reverse_migrate_posts),
    ]
